import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios';

const ChatBot = ({ onClose }) => {
  const [messages, setMessages] = useState([
    { 
      text: "Hello! I'm your teaching assistant powered by AI. How can I help you today?", 
      sender: 'bot',
      timestamp: new Date()
    }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [aiModel, setAiModel] = useState('gpt-4'); // Default AI model
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (input.trim() === '') return;

    // Add user message
    const userMessage = { 
      text: input, 
      sender: 'user',
      timestamp: new Date()
    };
    
    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    try {
      // Simulate API call to AI model
      let response;
      const userQuery = input.trim().toLowerCase();
      
      // Check for model switching commands
      if (userQuery === 'use chatgpt' || userQuery === 'switch to chatgpt') {
        setAiModel('gpt-4');
        response = "I've switched to ChatGPT model for answering your questions.";
      } else if (userQuery === 'use gemini' || userQuery === 'switch to gemini') {
        setAiModel('gemini');
        response = "I've switched to Gemini model for answering your questions.";
      } else if (userQuery.includes('generate') && 
                (userQuery.includes('questions') || userQuery.includes('quiz')) && 
                userQuery.includes('sri lanka') && 
                (userQuery.includes('heritage') || userQuery.includes('history'))) {
        // Special case for Sri Lanka heritage questions
        response = await generateSriLankaHeritageQuestions();
      } else {
        // Simulate AI response with a delayed response
        response = await getAIResponse(userQuery);
      }

      setTimeout(() => {
        setMessages(prev => [...prev, { 
          text: response, 
          sender: 'bot',
          model: aiModel,
          timestamp: new Date()
        }]);
        setIsTyping(false);
      }, 1500);
    } catch (error) {
      console.error('Error getting AI response:', error);
      setTimeout(() => {
        setMessages(prev => [...prev, { 
          text: "I'm having trouble connecting to my AI services. Please try again later or ask another question.", 
          sender: 'bot',
          timestamp: new Date()
        }]);
        setIsTyping(false);
      }, 1000);
    }
  };

  const getAIResponse = async (query) => {
    // This would be a real API call in production
    // Simulating API call response time
    return new Promise((resolve) => {
      setTimeout(() => {
        const baseResponses = getBotResponse(query);
        const aiModelName = aiModel === 'gpt-4' ? 'ChatGPT' : 'Gemini';
        
        // Add AI model signature and more advanced formatting
        resolve(`${baseResponses}\n\n_Response generated by ${aiModelName}_`);
      }, 1000);
    });
  };

  const generateSriLankaHeritageQuestions = async () => {
    // In a real implementation, this would call an AI API
    // For now, we'll return pre-defined questions
    return new Promise((resolve) => {
      const questions = [
        {
          type: "Historical Site",
          question: "Which ancient city in Sri Lanka is known as the first capital of the country?",
          answer: "Anuradhapura",
          hint: "It's a UNESCO World Heritage site founded in 377 BC"
        },
        {
          type: "Cultural Heritage",
          question: "What is the name of the famous Sri Lankan festival where a tooth relic of Lord Buddha is paraded through the streets?",
          answer: "Esala Perahera",
          hint: "It's held in Kandy during July-August"
        },
        {
          type: "Ancient Monument",
          question: "What is the name of the ancient rock fortress in Sri Lanka that has beautiful frescoes?",
          answer: "Sigiriya",
          hint: "Also known as Lion Rock"
        },
        {
          type: "National Symbol",
          question: "What is the national tree of Sri Lanka?",
          answer: "Na Tree",
          hint: "Also known as Ironwood"
        },
        {
          type: "Historical Figure",
          question: "Who was the first king to unify Sri Lanka?",
          answer: "King Devanampiya Tissa",
          hint: "He ruled during the 3rd century BC"
        },
        {
          type: "Ancient Engineering",
          question: "What are the ancient irrigation reservoirs in Sri Lanka called?",
          answer: "Tanks",
          hint: "Also known as 'Wewa'"
        },
        {
          type: "Cave Temple",
          question: "Which cave temple in Sri Lanka contains paintings and statues dating back to the 1st century BC?",
          answer: "Dambulla",
          hint: "It's also known as the Golden Temple"
        },
        {
          type: "Traditional Art",
          question: "What is the traditional Sri Lankan art of decorating fabric with wax and dye called?",
          answer: "Batik",
          hint: "This method uses wax to create patterns"
        },
      ];
      
      const aiModelName = aiModel === 'gpt-4' ? 'ChatGPT' : 'Gemini';
      const result = `Here are some MCQ questions about Sri Lankan heritage for grade 4 students generated using ${aiModelName}:\n\n\`\`\`json\n${JSON.stringify(questions, null, 2)}\n\`\`\`\n\nYou can use these questions in your assignments or classroom activities.`;
      resolve(result);
    });
  };

  const getBotResponse = (message) => {
    // Simple response logic based on keywords
    if (message.includes('hello') || message.includes('hi') || message.includes('hey')) {
      return "Hello! How can I assist you with your teaching today?";
    } else if (message.includes('assignment') || message.includes('homework')) {
      return "I can help you create or manage assignments. Would you like to create a new assignment or check pending ones?";
    } else if (message.includes('report') || message.includes('generate report')) {
      return "You can generate reports from the dashboard. Click on the 'Generate Report' button to download a PDF of your teaching activity.";
    } else if (message.includes('student') || message.includes('progress')) {
      return "To view student progress, go to the Students section from the quick actions menu. There you can see detailed analytics for each student.";
    } else if (message.includes('schedule') || message.includes('timetable')) {
      return "Your current schedule is:\nMon - Wed: 8:00 AM - 3:00 PM\nThu - Fri: 9:00 AM - 4:00 PM";
    } else if (message.includes('help') || message.includes('support')) {
      return "I can help with:\n- Assignment creation\n- Student progress tracking\n- Report generation\n- Schedule information\n- Teaching resources\n- Generating quiz questions\nJust ask me about any of these topics!";
    } else if (message.includes('thank')) {
      return "You're welcome! Let me know if you need anything else.";
    } else if (message.includes('bye') || message.includes('goodbye')) {
      return "Goodbye! Have a great day teaching!";
    } else if (message.includes('resource') || message.includes('material')) {
      return "You can find teaching resources in the Resources section. Would you like some recommendations for your subject?";
    } else if (message.includes('generate') && message.includes('question')) {
      return "I can generate questions for various subjects using AI. Try asking me to 'generate some questions for Sri Lanka heritage for grade 4 students' or specify another topic and grade level.";
    } else if (message.includes('model') || message.includes('ai')) {
      return `I'm currently using the ${aiModel === 'gpt-4' ? 'ChatGPT' : 'Gemini'} model to generate responses. You can switch models by typing 'use ChatGPT' or 'use Gemini'.`;
    } else {
      return "I'm analyzing your question using AI. Could you please provide more details about what you're looking for? You can ask about assignments, reports, students, schedules, resources, or generating quiz questions.";
    }
  };

  const formatTime = (date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className="fixed bottom-4 right-4 w-80 h-96 bg-white rounded-lg shadow-xl flex flex-col overflow-hidden z-50">
      {/* Header */}
      <div className="bg-primary text-white px-4 py-3 flex justify-between items-center">
        <div className="flex items-center">
          <h3 className="font-medium">AI Teaching Assistant</h3>
          <span className="ml-2 text-xs bg-white/20 px-2 py-0.5 rounded-full">
            {aiModel === 'gpt-4' ? 'ChatGPT' : 'Gemini'}
          </span>
        </div>
        <button onClick={onClose} className="text-white hover:text-gray-200">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      
      {/* Messages */}
      <div className="flex-1 p-4 overflow-y-auto bg-gray-50">
        {messages.map((msg, index) => (
          <div 
            key={index} 
            className={`mb-3 ${msg.sender === 'user' ? 'text-right' : ''}`}
          >
            <div 
              className={`inline-block rounded-lg px-4 py-2 max-w-[80%] ${
                msg.sender === 'user' 
                  ? 'bg-primary text-white rounded-br-none' 
                  : 'bg-white shadow-sm text-gray-800 rounded-bl-none'
              }`}
            >
              <div dangerouslySetInnerHTML={{ __html: msg.text.replace(/\n/g, '<br />') }} />
              {msg.model && (
                <div className="mt-2 pt-2 border-t border-gray-200 text-xs text-gray-500 italic">
                  Powered by {msg.model === 'gpt-4' ? 'ChatGPT' : 'Gemini'}
                </div>
              )}
            </div>
            <div className="text-xs text-gray-500 mt-1">
              {formatTime(msg.timestamp)}
            </div>
          </div>
        ))}
        {isTyping && (
          <div className="mb-3">
            <div className="inline-block bg-white shadow-sm rounded-lg px-4 py-2 text-gray-800 rounded-bl-none">
              <div className="flex space-x-1">
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>
      
      {/* Input */}
      <form onSubmit={handleSendMessage} className="bg-white border-t p-2 flex">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask me anything..."
          className="flex-1 border rounded-l-lg px-3 py-2 focus:outline-none focus:ring-1 focus:ring-primary"
        />
        <button
          type="submit"
          className="bg-primary text-white px-4 py-2 rounded-r-lg hover:bg-primary/90"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
          </svg>
        </button>
      </form>
      
      {/* Model selector buttons */}
      <div className="bg-gray-100 border-t px-2 py-1 flex justify-center space-x-2 text-xs">
        <button 
          onClick={() => setAiModel('gpt-4')}
          className={`px-2 py-1 rounded ${aiModel === 'gpt-4' ? 'bg-blue-500 text-white' : 'bg-gray-200 text-gray-700'}`}
        >
          ChatGPT
        </button>
        <button 
          onClick={() => setAiModel('gemini')}
          className={`px-2 py-1 rounded ${aiModel === 'gemini' ? 'bg-green-500 text-white' : 'bg-gray-200 text-gray-700'}`}
        >
          Gemini
        </button>
      </div>
    </div>
  );
};

export default ChatBot; 